### ISSUE TITLE
Problem when using Steam in another language

### ISSUE THREAD

**Issue by joaopedrosgs** [kirksaunders/sunshine-steam-adapter#1]
Hey, first of all, thanks for this application =)

I just had one problem. Since I'm using Steam in PT-BR, the application could not find the Big Picture window, given that the name is hardcoded as "Steam Big Picture Mode". For my use case, I've just replaced the string and it worked.

Obs: in PT-BR, the window title is "Steam — Modo Big Picture"

**Comment by kirksaunders** [comment]
Thanks for the report! Steam writes the language to a registry key, so I can read that use the correct window title.

**Comment by kirksaunders** [comment]
I pushed a commit to add support for all languages that Steam supports. Feel free to reopen this issue if it doesn't work for you :)
