### ISSUE TITLE
** Suggestion/feature ** Pull from playnite option

### ISSUE THREAD

**Issue by cooljimy84** [kirksaunders/sunshine-steam-adapter#2]
Steams has most of my games, but all of my games are in playnight. would be kool to pull the list from there as well/rather than steam ?

Feel free to close this, just a thought.

**Comment by kirksaunders** [comment]
I created this tool to avoid needing third party launchers (like Playnite), opting instead to use Steam for all games. If your games are in Playnite already, I would recommend just launching Playnite from Sunshine/Moonlight.
